### ISSUE TITLE
Add the option to specify additional repositories

### ISSUE THREAD

**Issue by abique** [revapi/diff.revapi.org#1]
Hi,

I'd need to compare something in https://maven.bitwig.com so I think it would be convenient to have an option to add additional repositories.

What do you think?

Thanks,
Alex

**Comment by metlos** [comment]
That would be interesting but since I'm paying for the service myself, I don't want to blow it up too much :) Also, it is essentially a thin wrapper around revapi itself, so it should be relatively easy to use revapi CLI for this purpose - it actually already supports specifying custom remote repos.. Just download the CLI from https://revapi.org/downloads.html, unzip and run `revapi.sh -h` to get the usage.
